jobs:
  build-libp2p:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'

      - run: |
          cd vendor/libp2p
          chmod +x gradlew
          ./gradlew clean build -x test

  build-java-tron:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '8'

      - run: |
          cd vendor/java-tron
          chmod +x gradlew
          ./gradlew clean build -x test
